import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PWP);
const b = await chromium.launch();
const p = await b.newPage();
const errs=[];
p.on('console', m=>{ if(m.type()==='error') errs.push(m.text()); });
p.on('pageerror', e=>errs.push('PAGEERROR: '+e.message));
await p.goto('https://www.studiofisyo.com/',{waitUntil:'networkidle'});
await p.waitForTimeout(2500);
console.log('===== ERRORI CONSOLE (live, tutti) =====');
[...new Set(errs)].forEach(e=>console.log('  • '+e.slice(0,140)));
if(!errs.length) console.log('  (nessuno)');
console.log('\n===== GERARCHIA HEADING (home) =====');
const heads = await p.$$eval('h1,h2,h3,h4,h5,h6', els=>els.map(e=>({t:e.tagName, txt:e.textContent.trim().slice(0,40)})));
let prev=0, skips=[];
heads.forEach(h=>{const lvl=+h.t[1]; if(prev && lvl>prev+1) skips.push(`${h.t} dopo H${prev}: "${h.txt}"`); prev=lvl;});
heads.slice(0,20).forEach(h=>console.log('  '+h.t+'  '+h.txt));
console.log('  --- salti: '+(skips.length?skips.join(' | '):'nessuno')+' ---');
await p.close(); await b.close();
